Update dependency Next.js to v9.1.4 (#315)
* Update Next.js to version 9.1.4

"Upgrade to latest release in a follow-up since they changed how they polyfill."
See https://github.com/mui-org/material-ui/pull/18441/files#r386433177.

* Move next.config.js out of "src" directory

Next.js supports "src" directory since version 9.1:
https://nextjs.org/blog/next-9-1#src-directory-support

* Move "packages/web/src/static" to "packages/web/public/static"

The public directory was also introduced in version 9.1:
https://nextjs.org/blog/next-9-1#public-directory-support.

* Autofix tsconfig.json after running "next"

npm run dev

* Remove @zeit/next-typescript/babel from .babelrc

https://nextjs.org/blog/next-9#built-in-zero-config-typescript-support

* Remove "prefetch" prop from usage of Link

Next.js "will automatically prefetch <Link> components as they appear
in-viewport" since version 9.0.

See:

- https://nextjs.org/blog/next-9#production-optimizations
- https://nextjs.org/docs/api-reference/next/link

* Remove Container from pages/_app.tsx

Container was deprecated in v9.0.4:
https://err.sh/zeit/next.js/app-container-deprecated

* Disable option "isolatedModules" in tsconfig.json

For now just to make the tests run in CI. Later we can
figure out if it's "declaration" that should go away.

* Fix unavailable next/router in getDataFromTree()

"Error while running `getDataFromTree` TypeError: Cannot read property
'pathname' of null".

There's a lot of code I added in this commit just to debug what was
going on, but the important part is the usage of `AppTree` instead
of the composed `App` when using `getDataFromTree()`.

The issue is documented here:
https://github.com/vercel/next.js/issues/7731

And solved here:
https://github.com/vercel/next.js/pull/7732

* Revert "Update Next.js to version 9.1.4"

This reverts commit bbc417dbdf08d5c35f6d44fdcf70d9912bf1635a.

* Update Next.js again after solving conflict...

...in package-lock.json

https://stackoverflow.com/a/54127283/1787829

* Fix next/router interface with nprogress in AppFrame

* Enable "isolatedModules" back in packages/web/tsconfig.json

Babel, through Next.js, need this very badly:

"The following changes are being made to your tsconfig.json file:
  - compilerOptions.isolatedModules must be true (requirement for babel)"

* Replace withRouter() with useRouter()

* Fix FakeLoadingProvider not being a module

"error TS1208: All files must be modules when
the '--isolatedModules' flag is provided."

* Replace NextFunctionComponent with NextPage type

* Replace NextContext to NextPageContext in next.d.ts

* Fix mockRouter types in MockNextContext

* Add @olimat/api back to package.json

I removed by mistake when updating Next.js in
274a008721c6bdbe25aed466c5f5f7e009dabadb

* Migrate MockNextContext to new context API

* Remove `as any` from MockNextContext router prop

* Add comment about Filepond's CSS in Next.js 9.0

* Disable 'composite' & 'declaration' in web/tsconfig.json

* Reword comment about isolatedModules in web/tsconfig.json

* Add `ls` to check node_modules/@olimat/api on CI

* Replace tabs with spaces in .circleci/config.yml

* Add more `ls` command to CI config

* Fix path in `ls` in CI config

* Separate building of api and web apps

* Fix CI config to build api before web app

* Change indent_style to spaces for yaml files and package.json

* Remove "env.test.presets" from .babelrc

* Replace withRouter() with useRouter() in Link

* Remove `ls` and `pwd` commands from CI config

* Fix next/router mock in ExamList test