Update dependency typescript to v3.9.5 (#278)
* Update dependency typescript to v3.9.5

* Update dependency typescript to v3.9.5

* Fix name clashes in resolvers-types.ts with a hack

I modified indent_style back to "space" in .editorconfig to avoid too
much changes in this commit's diff.

We still have the following problem: "error TS5053: Option 'noEmit'
cannot be specified with option 'composite'."

* Add --composite false to "typecheck:api" npm command

TypeScript incremental build seems to be a problem for projects using
Babel, like Next.js apps:

"error TS5053: Option 'noEmit' cannot be specified with option 'composite'."

So... https://github.com/microsoft/TypeScript/issues/36917

* Suppress TS errors from mocked server context

* Fix *Payload interfaces with a temporary hack

* Fix directories in VS Code workspace config

* Add --composite false to "typecheck:web" npm command

* Add tsconfig.build.json to avoid incremental build

For package/web, which uses Babel.

* Replace GlobalFetch with WindowOrWorkerGlobalScope

GlobalFetch was removed in TS 3.6.2:
https://github.com/apollographql/apollo-link/issues/1131

* Fix root "build" command to use tsconfig.build.json

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Josias Iquabius <iquabius@gmail.com>